name: CI do Gateway de Pagamentos

on:
  push:
    branches: [ mas ]
  pull_request:
    branches: [ main ]

jobs:
  build:
   
    runs-on: ubuntu-latest
    
    steps:
   
    - name: Checkout do código
      uses: actions/checkout@v4

   
    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    
    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest httpx flake8

    
    - name: Rodar o Flake8 Linter
      run: |
        flake8 app/ --count --max-complexity=10 --max-line-length=127 --ignore=E203,E501,W503 --show-source --statistics

    
    - name: Rodar os testes
      run: pytest app/tests/
